lib/database.dart, lib/l10n/app_en.arb, lib/models/db/server.dart, lib/objectbox-model.json, lib/objectbox.g.dart, lib/service.dart, lib/utils.dart, lib/views/settings/manageServerInner.dart, lib/views/settings/manageSingleServer.dart
=> add option to login with cookies

lib/myRouteObserver.dart, lib/views/settings.dart, lib/views/settings/manageServerInner.dart, lib/views/video/player.dart
fixes #29
fix issue where mini player was not positionned properly in server management tabs
=> Fix theming of  video overlay options

lib/controllers/miniPayerController.dart, lib/views/videoPlayer/videoQueue.dart
fix issue that allowed user to tap on the currently playing video in the video queue  that would restart the video
=> fix bug that prevented to move currently playing video

lib/controllers/miniPayerController.dart, lib/controllers/miniplayerControlsController.dart, lib/views/components/videoLikeButton.dart, lib/views/miniPlayer.dart, lib/views/playlistView.dart, lib/views/videoPlayer/fullScreenView.dart, lib/views/videoPlayer/miniPlayerControls.dart, lib/views/videoPlayer/miniPlayerView.dart
fix comments not changing after playing a new video in the video player make video list behavior consistent (swipe to remove, normal tap for standard action)
=> fix height of bottom navigation bar on the video player

lib/controllers/settingsController.dart, lib/database.dart, lib/l10n/app_en.arb, lib/main.dart, lib/utils.dart, lib/views/channel.dart, lib/views/miniPlayer.dart, lib/views/playlistView.dart, lib/views/settings.dart, lib/views/settings/manageServers.dart, lib/views/settings/manageSingleServer.dart, lib/views/settings/sponsorBlockSettings.dart, lib/views/video.dart, lib/views/videoPlayer/fullScreenView.dart
=> Revert "add true black mode for oled screen users"

pubspec.lock
=> add playback speed up to 6x

lib/views/tv/tvHome.dart, pubspec.yaml
Fix https://github.com/lamarios/clipious/issues/151
=> Fix search text localisation on TV

lib/l10n/app_en.arb, lib/service.dart, lib/views/channel.dart, lib/views/tv/tvChannelView.dart
=> add shorts to channel view

android/app/src/main/AndroidManifest.xml
Fix https://github.com/lamarios/clipious/issues/176
=> Add more youtube URIs to intent filter

lib/models/baseVideo.dart, lib/models/video.dart, lib/views/components/videoShareButton.dart, lib/views/miniPlayer.dart, lib/views/video.dart, pubspec.lock, pubspec.yaml
=> add share button on the video player view

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I dont know if you want Issue Templates, but i am bored so i changed up the default ones a bit and made this Pull Request.
=> Issue Templates 

lib/player/views/components/player_controls.dart
=> fix modal sheet stopping at half screen in landscape mode

android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/com/github/lamarios/clipious/MainActivity.kt, lib/player/models/mediaEvent.dart, lib/player/states/player.dart, lib/player/states/video_player.dart, lib/player/views/components/player_controls.dart, lib/settings/views/components/manager_server_inner.dart, lib/settings/views/screens/settings.dart, lib/settings/views/tv/components/manage_server_inner.dart, lib/settings/views/tv/screens/settings.dart, pubspec.lock, pubspec.yaml
add ignore ssl certification option in server management screen, so it appears on first time set up ( fix #293 #265 )
fix issues with back button when on full screen
fix issues when switching video within picture in picture mode add possibility to use previous / next buttons in pip mode add video title to full screen video view
reduce opacity of video controls background ( fix #236 )
=> Issue fix batch

lib/main.dart, pubspec.lock, pubspec.yaml
=> force high refresh rate because sometimes flutter is stuck at 60hz

lib/player/states/tv_player_controls.dart, lib/utils.dart, lib/videos/views/tv/components/video_item.dart, pubspec.yaml
=> Add more events for select/  ok events on TV

lib/service.dart
Fix https://github.com/lamarios/clipious/issues/330
=> Fix unicode search suggestions containing whitespace

lib/app/views/tv/screens/tv_home.dart, lib/home/models/db/home_layout.dart, lib/playlists/views/tv/screens/playlist.dart, lib/router.dart, lib/router.gr.dart, lib/service.dart, lib/settings/models/db/video_filter.dart, lib/settings/states/settings.dart, lib/settings/states/video_filter_edit.dart, lib/settings/views/screens/video_filter_setup.dart, lib/settings/views/tv/screens/app_layout.dart, lib/settings/views/tv/screens/filter_edit.dart, lib/settings/views/tv/screens/filter_list.dart, lib/settings/views/tv/screens/settings.dart, lib/utils.dart, lib/utils/states/tv/searchable_dynamic_select_from_list.dart, lib/utils/states/tv/searchable_dynamic_select_from_list.g.dart, lib/utils/states/tv/time_picker.dart, lib/utils/video_post_processing.dart, lib/utils/views/tv/components/searchable_dynamic_select_from_list.dart, lib/utils/views/tv/components/tv_text_field.dart, lib/utils/views/tv/components/tv_time_picker.dart, lib/videos/views/components/trending.dart, lib/videos/views/components/video_list.dart, lib/videos/views/tv/components/video_item.dart, lib/videos/views/tv/screens/video.dart
add home customization to TV
fix #366
=> add video filtering to TV

lib/search/states/search.dart
=> remove search suggestions from distraction free mode

lib/l10n/app_en.arb, lib/service.dart, lib/settings/models/errors/cannot_add_server_error.dart, lib/settings/models/errors/missing_software_key.dart, lib/settings/models/errors/unreacheable_server.dart, lib/settings/states/server_list_settings.dart, lib/settings/views/components/manager_server_inner.dart, lib/settings/views/tv/components/manage_server_inner.dart
=> add fix to better describe errors when adding servers

lib/player/states/player.dart, pubspec.lock, pubspec.yaml
=> fix issues with fullscreen switch on landscape phone

lib/player/states/video_player.dart, lib/settings/states/video_filter_edit.dart
Fix issue where the "Filter all videos for channel" would not appear when creating a new filter
Fix issue where changing video resolution on a non dash video would not work
=> Small fixes

lib/settings/views/screens/manage_single_server.dart, lib/utils.dart
make sure dialog positive action is always on the same side
=> Standardize dialog action positions

lib/app/states/app.dart, lib/app/states/app.freezed.dart, lib/app/views/screens/main.dart, lib/l10n/app_fr.arb, lib/playlists/views/components/add_to_playlist_list.dart, lib/search/views/components/search_filters.dart, lib/settings/states/settings.dart, lib/settings/views/components/manager_server_inner.dart, lib/settings/views/screens/appearance.dart, lib/settings/views/screens/browsing.dart, lib/settings/views/screens/manage_single_server.dart, lib/utils.dart, lib/utils/views/components/select_list_dialog.dart, lib/videos/views/components/add_to_playlist_dialog.dart
add global loading so the user knows something is happening (can be useful for later)
=> fix feedback and dialog issues

android/app/src/main/AndroidManifest.xml
=> allow http traffic

lib/l10n/app_en.arb, lib/service.dart, lib/settings/models/db/settings.dart, lib/settings/states/settings.dart, lib/settings/views/screens/browsing.dart, lib/settings/views/tv/screens/settings.dart
=> allow custom RYD url

lib/app/states/app.dart
=> fix issues with app links not opening the related video

lib/l10n/app_en.arb
Fixed a typo and improved grammar
=> improve warning message when the user enables dearrow

lib/channels/views/components/info.dart, lib/videos/models/video.dart, lib/videos/models/video.g.dart, pubspec.yaml
fix issue where server are missing channel banner
fix #569
=> fix issue where servers are missing the genreUrl

lib/home/models/db/home_layout.dart, lib/l10n/app_en.arb, lib/l10n/app_fr.arb, lib/offline_subscriptions/models/offline_subscription.dart, lib/offline_subscriptions/models/offline_subscription.freezed.dart, lib/offline_subscriptions/models/offline_subscription.g.dart, lib/subscription_management/states/manage_subscriptions.dart, lib/subscription_management/states/manage_subscriptions.freezed.dart, lib/subscription_management/states/subscribe_button.dart, lib/subscription_management/states/subscribe_button.freezed.dart, lib/subscription_management/view/components/subscribe_button.dart, lib/subscription_management/view/screens/manage_subscriptions.dart, lib/subscription_management/view/tv/tv_subscribe_button.dart, lib/utils/extensions/list_unique.dart, lib/utils/file_db.dart, lib/utils/interfaces/db.dart, lib/utils/models/paginated_list.dart, lib/utils/sembast_sqflite_database.dart, lib/videos/views/components/video_list.dart, pubspec.yaml
=> offline subscriptions

.drone.yml, .github/workflows/build.yml, .github/workflows/release.yml, android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml, lib/service.dart, pubspec.lock, pubspec.yaml
Use cronet_http on Android for support certificates from user storage and changes in manifest for fix play video in proxy mode with selfsigned certs
=> Android: support users certificates and fix video play with selfsigned proxy

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/settings.gradle, lib/downloads/models/downloaded_video.dart, lib/downloads/states/download_manager.dart, lib/downloads/views/components/downloaded_video.dart, lib/downloads/views/screens/download_manager.dart, lib/l10n/app_en.arb, lib/player/states/audio_player.dart, lib/player/states/video_player.dart, lib/videos/states/download_modal_sheet.dart, lib/videos/states/download_modal_sheet.freezed.dart, lib/videos/views/components/download_modal_sheet.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
add way to copy video to download folder
make downloaded video actions more obvious
=> add more video download options

lib/channels/views/components/info.dart, lib/channels/views/tv/screens/channel.dart, lib/comments/views/components/comment.dart, lib/home/models/db/home_layout.g.dart, lib/player/views/components/audio_player.dart, lib/player/views/tv/components/player_controls.dart, lib/playlists/views/components/playlist_in_list.dart, lib/playlists/views/components/playlist_inner_view.dart, lib/playlists/views/components/playlist_thumbnail.dart, lib/playlists/views/tablet/playlist_inner_view.dart, lib/playlists/views/tv/screens/playlist.dart, lib/settings/models/db/video_filter.g.dart, lib/settings/views/components/video_filter_channel.dart, lib/utils/models/image_object.dart, lib/utils/states/thumbnail.dart, lib/utils/states/thumbnail.freezed.dart, lib/utils/views/components/thumbnail.dart, lib/videos/models/video.dart, lib/videos/views/components/compact_video.dart, lib/videos/views/components/info.dart, lib/videos/views/components/inner_view.dart, lib/videos/views/components/inner_view_tablet.dart, lib/videos/views/components/video_in_list.dart, lib/videos/views/components/video_thumbnail.dart, lib/videos/views/tv/components/video_item.dart, lib/videos/views/tv/screens/video.dart
put server url in case thumbnails are not configured properly
=> add fallback to make sure the thumbnail fails as little as possible

lib/globals.dart, lib/http_overrides.dart, lib/main.dart, lib/settings/states/settings.dart, pubspec.yaml
=> change user agent to be Clipious/version

.github/ISSUE_TEMPLATE/bug_report.md
- Renamed Smartphone Section to General Information
- Added Invidious-Instance to General Information
- Added a Colon behind Version
=> Update bug_report.md - Added Instance-Information

lib/videos/models/video.dart, lib/videos/models/video.freezed.dart, lib/videos/models/video.g.dart, shell.nix
=> fix issues with latest version of invidious

lib/l10n/app_en.arb, lib/settings/models/db/settings.dart, lib/settings/states/settings.dart, lib/settings/views/screens/appearance.dart, lib/settings/views/tv/screens/settings.dart, lib/utils.dart, lib/videos/models/video.dart, lib/videos/models/video.freezed.dart, lib/videos/models/video.g.dart
=> add settings to force the TV ui, can be useful for some tv boxes

android/app/build.gradle, lib/downloads/states/download_manager.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
=> fix ffmpeg

android/app/build.gradle, lib/downloads/states/download_manager.dart, lib/settings/states/server_list_settings.dart, lib/settings/views/components/manager_server_inner.dart, lib/settings/views/tv/components/manage_server_inner.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, test/settings/state/server_list_settings_test.dart
=> remove public servers in the server manager

lib/videos/views/components/add_to_playlist_button.dart, lib/videos/views/components/video_modal_sheet.dart
=> fix some layout issues

lib/player/views/components/mini_player_aware.dart, lib/player/views/components/player.dart, lib/videos/views/components/download_modal_sheet.dart, lib/videos/views/components/video_modal_sheet.dart, pubspec.yaml
=> fix layout issues

pubspec.yaml
=> upgade flutter to re-enable f-droid builds
